//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisWebVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public int CVE_PERSONA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_S { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual VENDEDOR VENDEDOR { get; set; }
    }
}
