//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisWebVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.DETALLE_VENTAS = new HashSet<DETALLE_VENTAS>();
        }
    
        public int CVE_PRODUCTO { get; set; }
        public Nullable<int> CVE_MARCA { get; set; }
        public Nullable<int> CVE_TIPO_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> EXISTENCIA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<float> PRECIO { get; set; }
        public string CLAVE { get; set; }
        public Nullable<decimal> STOCK_MAXIMO { get; set; }
        public Nullable<decimal> STOCK_MINIMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTAS> DETALLE_VENTAS { get; set; }
        public virtual MARCAS MARCAS { get; set; }
        public virtual TIPO_PRODUCTOS TIPO_PRODUCTOS { get; set; }
    }
}
