//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisWebVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        public int CVE_VENDEDOR { get; set; }
        public Nullable<int> CVE_PERSONA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual PERSONAS PERSONAS { get; set; }
    }
}
