//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisWebVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int FOLIO_VENTA { get; set; }
        public Nullable<int> FOLIO_FACTURA { get; set; }
        public Nullable<int> CVE_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_VENTA { get; set; }
        public Nullable<bool> PAGADO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<bool> DEVUELTO { get; set; }
    
        public virtual DETALLE_VENTAS DETALLE_VENTAS { get; set; }
        public virtual FACTURAS FACTURAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
